# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'ValifyApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ValifyApp
   pod 'ValifyCapture', '~> 1.0.1'
#   pod 'Firebase/Core'
#   pod 'Firebase/MLVision'
#   pod 'Firebase/MLVisionFaceModel'
end
